version: "3.9"

services:
  # =====================
  # RabbitMQ (container)
  # =====================
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ipi_net

  # =====================
  # Products Service (MongoDB HOST)
  # =====================
  products:
    build: ./products
    container_name: products
    ports:
      - "8093:8093"
    restart: always
    depends_on:
      - rabbitmq
    volumes:
      - ./products:/app
      - /app/node_modules
    env_file:
      - ./products/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ipi_net

  # =====================
  # Users Service (MongoDB HOST)
  # =====================
  users:
    build: ./users
    container_name: users
    ports:
      - "8094:8094"
    restart: always
    depends_on:
      - rabbitmq
    volumes:
      - ./users:/app
      - /app/node_modules
    env_file:
      - ./users/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ipi_net

  # =====================
  # Stores Service (MongoDB HOST)
  # =====================
  stores:
    build: ./stores
    container_name: stores
    ports:
      - "8095:8095"
    restart: always
    depends_on:
      - rabbitmq
    volumes:
      - ./stores:/app
      - /app/node_modules
    env_file:
      - ./stores/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ipi_net

  # =====================
  # Shopping Service (MySQL HOST)
  # =====================
  shopping:
    build: ./shopping
    container_name: shopping
    ports:
      - "8096:8096"
    restart: always
    depends_on:
      - rabbitmq
    volumes:
      - ./shopping:/app
      - /app/node_modules
    env_file:
      - ./shopping/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ipi_net

  # =====================
  # Nginx Reverse Proxy
  # =====================
  nginx-proxy:
    build: ./proxy
    container_name: nginx-proxy
    ports:
      - "8081:80"
    depends_on:
      - products
      - users
      - stores
      - shopping
    networks:
      - ipi_net

networks:
  ipi_net:
    driver: bridge
