worker_processes auto;

events {
    worker_connections 1024;
}

http {

    server {
        listen 80;
        charset utf-8;

        location /products/ {
            proxy_pass http://products:8093/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /users/ {
            proxy_pass http://users:8094/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /stores/ {
            proxy_pass http://stores:8095/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /shopping/ {
            proxy_pass http://shopping:8096/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
